# Generated by Django 5.0.7 on 2024-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
