# Generated by Django 5.0.7 on 2024-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
