# Generated by Django 5.0.7 on 2024-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.SlugField(),
        ),
    ]
