# Generated by Django 5.0.7 on 2024-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
